name: myjym
description: Personal workout planning done for you!

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  video_player: ^2.4.2
#  flutter_video_compress: ^0.3.x
  flutter:
    sdk: flutter


#  cupertino_icons: ^1.0.2
  flutter_dialogs: ^2.1.1
  numberpicker: ^2.0.1
  youtube_player_flutter: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/ui/
