name: myjym
description: Personal workout planning done for you!

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


#  cupertino_icons: ^1.0.2
  flutter_dialogs: ^2.1.1
  numberpicker: ^2.0.1
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.6
  flutter_emoji: ">= 2.0.0"
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/ui/

  fonts:
    - family: MyJymIcons
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf