/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyJymIcons';
  static const String? _kFontPkg = null;

  static const IconData arm = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leg = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pull = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData push = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
